### ISSUE TITLE
Bcrypt 3.1.18 not working on Ubuntu 22.04.02 LTS

### ISSUE THREAD

**Issue by fahad-afzal** [bcrypt-ruby/bcrypt-ruby#269] opened 2023-06-20 13:12 UTC
We are wokring on an old rails project 
ruby 1.9.4
Rails 3.2.8

Which was using bcrypt 3.1.7 and it was working fine on Ubuntu 18.
Then we moved on to Ubuntu 20 so, we used bcrypt 3.1.16 and it worked fine.

Now we have installed Ubuntu 22 and I've moved the bcrypt version to 3.1.18 ( Latest ) but it's not working now.

Anyone can help us in this regard? It'll be great otherwise we have to downgrade to Ubuntu 20 again.

Thanks!

**Comment by tenderlove** [comment] 2023-06-26 18:44
Hi @fahad-afzal,

I don't normally work with Ruby / Rails that are that old.  However, if you could post the errors you get when trying to install maybe I can help.  Thanks!

**Comment by tjschuck** [comment] 2023-06-26 20:37
@fahad-afzal For what it's worth, it's probably _not_ Ubuntu 22 that's the issue here.  The CI for bcrypt-ruby runs Ubuntu 22 as well — [here's the passing job](https://github.com/bcrypt-ruby/bcrypt-ruby/actions/runs/5349167787/jobs/9699998728) for Ruby 2.1 on Ubuntu 22.

Without more information, my guess is that the issue is Ruby 1.9, which reached EOL [more than 8 years ago](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/).

Like @tenderlove said, if you can provide some more info about what you're seeing, we might be able to help.  In the meantime, closing until more info is provided, but we'll reopen if/when you do.

**Closed by tjschuck** 2023-06-26 20:37 UTC
